# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_displayed', models.DateField(blank=True, null=True)),
                ('phrase', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('translation', models.TextField()),
            ],
        ),
    ]
