# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('date', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('insult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Insult')),
            ],
        ),
    ]
