# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insult',
            name='last_displayed',
        ),
        migrations.AlterField(
            model_name='day',
            name='insult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.Insult'),
        ),
    ]
